// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

import { implicitReturnType } from '../base/types.js';
import { Exchange as _Exchange } from '../base/Exchange.js';

interface Exchange {
    v1PublicGetInfoMarkets (params?: {}): Promise<implicitReturnType>;
    v1PublicGetInfoMarketsMarketStats (params?: {}): Promise<implicitReturnType>;
    v1PublicGetInfoMarketsMarketOrderbook (params?: {}): Promise<implicitReturnType>;
    v1PublicGetInfoMarketsMarketTrades (params?: {}): Promise<implicitReturnType>;
    v1PublicGetInfoCandlesMarketCandleType (params?: {}): Promise<implicitReturnType>;
    v1PublicGetInfoMarketFunding (params?: {}): Promise<implicitReturnType>;
    v1PublicGetInfoMarketOpenInterests (params?: {}): Promise<implicitReturnType>;
    v1PublicGetInfoBuilderDashboard (params?: {}): Promise<implicitReturnType>;
}
abstract class Exchange extends _Exchange {}

export default Exchange
